"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['deemix-pyweb.py']
DATA_FILES = ['icon.icns', 'webui/public']
OPTIONS = {
    'iconfile':'icon.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
